name: CI

on:
  push:
  schedule:
    - cron: '0 15 * * *'

jobs:
  test_linux:
    name: sbcl-bin on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: make test
  test_mac:
    name: sbcl-bin on macOS-latest
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: sbcl-bin
          ROSWELL_INSTALL_DIR: /usr
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install Ultralisp
        run: ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Install Rove
        run: ros install rove
      - name: Run tests
        run: |
          PATH="~/.roswell/bin:$PATH"
          rove qlot.asd
