name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Roswell
        env:
          LISP: sbcl
          ROSWELL_INSTALL_DIR: /usr
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Setup Qlot
        run: scripts/setup.sh
      - name: Bundle dependencies
        run: scripts/run.sh bundle
      - name: Create a bundled tarball
        run: tar --exclude './.git' --exclude './.qlot' -cvfz /tmp/qlot.tar.gz ./
      - name: Release and publish assets
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: /tmp/qlot.tar.gz
